name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          python-version: 3.12.4
    - name: Run Django unit tests
      run: |
        pip3 install --user django
        python3 manage.py test

